#!/usr/bin/env python3
"""Parse benchmark results and generate comparison tables."""

import json
import os
import sys
from pathlib import Path

RESULTS_DIR = Path(__file__).parent.parent / "results"

def load_results():
    """Load all JSON result files from results/ directory."""
    results = {}
    for f in sorted(RESULTS_DIR.glob("*.json")):
        name = f.stem.replace("bench_", "")
        try:
            with open(f) as fh:
                results[name] = json.load(fh)
        except (json.JSONDecodeError, IOError) as e:
            print(f"Warning: Could not parse {f}: {e}")
    return results


def format_cell(ms):
    """Format a time value for the table."""
    if ms < 1.0:
        return f"{ms*1000:.1f}µs"
    elif ms < 1000:
        return f"{ms:.2f}ms"
    else:
        return f"{ms/1000:.2f}s"


def print_comparison_table(results):
    """Print the main comparison table across all benchmarks."""
    print("\n" + "=" * 80)
    print("PTX Micro-Benchmark Suite — Comparison Table")
    print("=" * 80)

    # Summary table: best case for each benchmark
    print("\n| Benchmark       |    Naive  | Optimized |      PTX  | Speedup |")
    print("|-----------------|-----------|-----------|-----------|---------|")

    for name, entries in results.items():
        if not entries:
            continue
        # Pick entry with most elements (largest scale)
        best = entries[-1] if isinstance(entries, list) else entries
        if isinstance(best, dict):
            naive = best.get("naive_ms", 0)
            opt = best.get("opt_ms", 0)
            ptx = best.get("ptx_ms", 0)
            speedup = naive / ptx if ptx > 0 else 0
            print(f"| {name:<15} | {format_cell(naive):>9} | {format_cell(opt):>9} | {format_cell(ptx):>9} | {speedup:>6.2f}x |")

    print()


def print_detailed_tables(results):
    """Print detailed per-benchmark tables with all scales."""
    for name, entries in results.items():
        if not entries:
            continue
        print(f"\n--- {name} ---")

        if not isinstance(entries, list):
            entries = [entries]

        if not entries:
            continue

        # Determine columns from first entry
        keys = list(entries[0].keys())
        time_keys = [k for k in keys if k.endswith("_ms")]

        # Build header
        scale_keys = [k for k in keys if k not in time_keys and k != "speedup"]
        header = " | ".join(scale_keys + ["Naive", "Optimized", "PTX", "Speedup"])
        print(f"| {header} |")
        print(f"|{'---|' * (len(scale_keys) + 4)}")

        for entry in entries:
            scale_vals = [str(entry.get(k, "?")) for k in scale_keys]
            naive = entry.get("naive_ms", 0)
            opt = entry.get("opt_ms", 0)
            ptx = entry.get("ptx_ms", 0)
            speedup = entry.get("speedup", naive/ptx if ptx > 0 else 0)
            row = scale_vals + [format_cell(naive), format_cell(opt), format_cell(ptx), f"{speedup:.2f}x"]
            print(f"| {' | '.join(row)} |")

    print()


def print_bandwidth_analysis(results):
    """Estimate memory bandwidth utilization."""
    print("\n--- Bandwidth Analysis (estimated) ---")
    print("(Assumes RTX 4050: 256 GB/s theoretical, 6 GB GDDR6)")
    print()

    # Rough estimates based on data movement
    for name, entries in results.items():
        if not isinstance(entries, list) or not entries:
            continue
        entry = entries[-1]
        ptx_ms = entry.get("ptx_ms", 0)
        if ptx_ms <= 0:
            continue
        # This is a rough estimate — actual depends on operation
        print(f"  {name}: PTX time = {format_cell(ptx_ms)}")


def generate_markdown_report(results):
    """Generate a markdown report file."""
    report_path = RESULTS_DIR.parent / "results" / "report.md"
    with open(report_path, "w") as f:
        f.write("# PTX Benchmark Results\n\n")
        f.write("Auto-generated by analyze.py\n\n")

        f.write("## Summary\n\n")
        f.write("| Benchmark | Naive | Optimized | PTX | Speedup |\n")
        f.write("|-----------|-------|-----------|-----|--------|\n")

        for name, entries in results.items():
            if not isinstance(entries, list) or not entries:
                continue
            best = entries[-1]
            naive = best.get("naive_ms", 0)
            opt = best.get("opt_ms", 0)
            ptx = best.get("ptx_ms", 0)
            speedup = naive / ptx if ptx > 0 else 0
            f.write(f"| {name} | {format_cell(naive)} | {format_cell(opt)} | {format_cell(ptx)} | {speedup:.2f}x |\n")

    print(f"Report saved to {report_path}")


def main():
    results = load_results()

    if not results:
        print("No results found in results/ directory.")
        print("Run 'make bench' first to generate benchmark data.")
        # Generate empty report template
        RESULTS_DIR.mkdir(parents=True, exist_ok=True)
        with open(RESULTS_DIR / "report.md", "w") as f:
            f.write("# PTX Benchmark Results\n\nNo results yet. Run `make bench` to generate.\n")
        return

    print_comparison_table(results)
    print_detailed_tables(results)
    generate_markdown_report(results)


if __name__ == "__main__":
    main()
